#!/bin/sh
ssh ubuntu@3.37.130.18 <<EOF
    cd ~/jenkins-tutorial
    git pull origin master
    curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
    . ~/.nvm/nvm.sh 
    nvm install 17.3.1
    npm install
    npm install -g pm2
    pm2 restart ecosystem.config.js
    exit
EOF

