#!/bin/sh
ssh ubuntu@3.37.130.18 <<EOF
    cd ~/jenkins-tutorial		//프로젝트를 풀받은 ec2에 들어있는 프로젝트이름
    git pull origin master
    curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
    . ~/.nvm/nvm.sh 
    nvm install 17.3.1	//젠킨스에서 설정한 node 버전
    npm install
    npm install -g pm2
    pm2 restart ecosystem.config.js
    exit
EOF

